# 基础镜像，指定从哪个镜像开始构建
FROM python:3.10-slim

# 安装OpenCV所需的系统依赖
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

# 安装Python依赖
# RUN pip install numpy==1.26.4 opencv_contrib_python==4.11.0.86 Pillow==11.1.0

# 升级pip
RUN pip install --upgrade pip

# 设置工作目录
WORKDIR /app

# 复制依赖文件并安装依赖
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/

# 复制项目文件到容器
COPY . .

# 容器启动时执行的命令
CMD ["python", "test_face.py"]