# 基础镜像，指定从哪个镜像开始构建
FROM python:3.10-slim

# 设置工作目录
WORKDIR /app

# 复制依赖文件并安装依赖
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 复制项目文件到容器
COPY . .

# 容器启动时执行的命令
CMD ["python", "test_face.py"]